# Generated by Django 4.1.7 on 2023-04-11 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipefile",
            name="mainImage",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
